/**
 * intentLM instrumentation manifest — framework-agnostic.
 *
 * View IDs are opaque strings (e.g. "app.portfolio"), never raw URLs or PII.
 * Only integer token IDs are sent to intentLM servers.
 */

/** View id → global token ID (same stability rules as URL patterns) */
export type ViewMap = Record<string, number>;

/** URL glob → token ID */
export type PatternMap = Record<string, number>;

/**
 * Customer manifest: public URL patterns + in-app views + optional core milestone.
 * Committed to the repo; generated by `intentlm scan` / setup, then edited.
 */
export interface IntentLMManifest {
  patterns: PatternMap;
  /** In-app screens (logged-in areas, tabs, wizards) — not sent as URLs */
  views?: ViewMap;
  /**
   * Structural onboarding milestone (600–699). Customer defines what "first value"
   * means; SDK emits this token via {@link IntentLMSDK.captureCoreAction}.
   */
  coreActionToken?: number;
}

/** Security tokens must not be mapped from the browser (spoofable). */
export function isBrowserForbiddenTokenId(tokenId: number): boolean {
  return tokenId >= 1000 && tokenId <= 1499;
}

const VIEW_ID_RE = /^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/;

/** Normalize and validate a view id (lowercase segments). */
export function normalizeViewId(raw: string): string | null {
  const id = raw.trim().toLowerCase().replace(/\s+/g, '.');
  if (!id || id.length > 80) return null;
  if (!VIEW_ID_RE.test(id)) return null;
  return id;
}

/**
 * Derive a stable view id from a URL path (for file-based / router discovery).
 * "/settings/billing" → "route.settings.billing"
 */
export function routePathToViewId(routePath: string): string {
  const trimmed = routePath.trim().replace(/\/+/g, '/');
  if (trimmed === '/' || trimmed === '') return 'route.home';
  const segments = trimmed
    .replace(/^\//, '')
    .split('/')
    .filter(Boolean)
    .map((seg) => {
      if (seg === '**' || seg === '*') return 'wildcard';
      if (seg.startsWith(':')) return seg.slice(1) || 'param';
      return seg.replace(/[^a-z0-9_-]/gi, '').toLowerCase() || 'segment';
    });
  return 'route.' + segments.join('.');
}

export interface ViewCoverageReport {
  /** View ids defined in config */
  expected: string[];
  /** View ids observed this session (browser-only, never uploaded by default) */
  seen: string[];
  /** expected minus seen */
  missing: string[];
}
